# Use usuario / senha como credenciais de usuário / senha
version: '3.8'

services:

 mongo:
   image: mongo
   restart: always
   environment:
    MONGO_INITDB_ROOT_USERNAME: usuario
    MONGO_INITDB_ROOT_PASSWORD: senha

 mongo-express:
   image: mongo-express
   restart: always
   ports:
     - 8081:8081
   environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: usuario
    ME_CONFIG_MONGODB_ADMINPASSWORD: senha
    ME_CONFIG_MONGODB_URL: mongodb://usuario:senha@mongo:27017/
